name: Build docker image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_VERSION: ${{ github.sha }}

jobs:
  build-docker-image:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: |
            ghcr.io/thirty-degrees/api-version-unsupported:${{ env.IMAGE_VERSION }}
            ghcr.io/thirty-degrees/api-version-unsupported:latest
          platforms: linux/arm64
          cache-from: type=registry,ref=ghcr.io/thirty-degrees/api-version-unsupported:buildcache
          cache-to: type=registry,ref=ghcr.io/thirty-degrees/api-version-unsupported:buildcache,mode=max
